# Generated by Django 4.1.1 on 2022-10-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_displaypicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imageString', models.TextField()),
                ('htmlFile', models.TextField(blank=True, null=True)),
                ('no_of_clicks', models.IntegerField(default=0)),
                ('hashtag1', models.CharField(blank=True, max_length=50, null=True)),
                ('hashtag2', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
