# Generated by Django 4.1.1 on 2022-10-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flier_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Displaypicture',
        ),
    ]
