# Generated by Django 4.1.1 on 2022-10-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_flier_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flier',
            name='hashtag2',
        ),
    ]
