# Generated by Django 4.1.1 on 2022-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_flier_hashtag2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flier',
            name='htmlFile',
        ),
        migrations.AddField(
            model_name='flier',
            name='image_height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flier',
            name='image_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flier',
            name='image_top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flier',
            name='image_width',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
