# Generated by Django 4.1.1 on 2022-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_flier_htmlfile_flier_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flier',
            name='htmlFile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
