# Generated by Django 4.1.1 on 2022-10-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_flier_image_height_alter_flier_image_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflier',
            name='flier_image',
            field=models.ImageField(default='r.jpg', upload_to='user_fliers'),
        ),
        migrations.AlterField(
            model_name='userflier',
            name='image',
            field=models.ImageField(default='r.jpg', upload_to='user_flier_images'),
        ),
    ]
